apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu-poc
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ubuntu-poc
  template:
    metadata:
      labels:
        app: ubuntu-poc
    spec:
      containers:
      - name: ubuntu-poc-demo
        image: priyankachouk/ubuntu-new1:latest
